/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mhnatko.ljubavnikalkulator;

import java.awt.TextField;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Miron
 */
public class LjubavniKalkulator extends javax.swing.JFrame {

    /**
     * Creates new form LjubavniKalkulator
     */
    public LjubavniKalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPrvaOsoba = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDrugaOsoba = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRezultat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnPokusajPonovno = new javax.swing.JButton();
        btnRezultat = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtPrvaOsoba.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPrvaOsoba.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrvaOsobaKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Ime i prezime prve osobe");

        txtDrugaOsoba.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtDrugaOsoba.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDrugaOsobaKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Ime i prezime druge osobe");

        txtRezultat.setEditable(false);
        txtRezultat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtRezultat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRezultatActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Rezultat");

        btnPokusajPonovno.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPokusajPonovno.setText("Pokušaj ponovno");
        btnPokusajPonovno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokusajPonovnoActionPerformed(evt);
            }
        });

        btnRezultat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRezultat.setText("Rezultat");
        btnRezultat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRezultatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPokusajPonovno)
                        .addGap(37, 37, 37)
                        .addComponent(btnRezultat)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPrvaOsoba, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(txtDrugaOsoba)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRezultat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrvaOsoba, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRezultat, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addComponent(txtDrugaOsoba, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPokusajPonovno)
                    .addComponent(btnRezultat))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPokusajPonovnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokusajPonovnoActionPerformed
        
    txtPrvaOsoba.setText("");
    txtDrugaOsoba.setText("");
    txtRezultat.setText("");
       
    }//GEN-LAST:event_btnPokusajPonovnoActionPerformed

    private void btnRezultatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRezultatActionPerformed
    
    String s1 = txtPrvaOsoba.getText();
    String s2 = txtDrugaOsoba.getText();
    
    int sum1=0,sum2=0;    
    for(int i=0;i<s1.length();i++){
        char ch = s1.charAt(i);
        int ascii = ch;
        sum1=sum1+ascii;
    }    
    for(int i=0;i<s2.length();i++){
        char ch = s2.charAt(i);
        int ascii = ch;
        sum2=sum2+ascii;
    }  
    
    int ukupno = sum1 + sum2;
    int ljubavPostotak = ukupno%100;
    txtRezultat.setText(ljubavPostotak + "%");
    }//GEN-LAST:event_btnRezultatActionPerformed

    private void txtRezultatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRezultatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRezultatActionPerformed

    private void txtPrvaOsobaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrvaOsobaKeyReleased
        txtPrvaOsoba.setText(txtPrvaOsoba.getText().toLowerCase());
    }//GEN-LAST:event_txtPrvaOsobaKeyReleased

    private void txtDrugaOsobaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDrugaOsobaKeyReleased
        txtDrugaOsoba.setText(txtDrugaOsoba.getText().toLowerCase());
    }//GEN-LAST:event_txtDrugaOsobaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LjubavniKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LjubavniKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LjubavniKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LjubavniKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LjubavniKalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPokusajPonovno;
    private javax.swing.JButton btnRezultat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtDrugaOsoba;
    private javax.swing.JTextField txtPrvaOsoba;
    private javax.swing.JTextField txtRezultat;
    // End of variables declaration//GEN-END:variables
}
